-- Optional: Use Snowflake for bookmarks (alternative to SQLite)
-- Run if you prefer Snowflake over SQLite for user bookmarks

CREATE TABLE IF NOT EXISTS LENS_USERS (
    ID          VARCHAR(36) PRIMARY KEY,
    USERNAME    VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LENS_BOOKMARKS (
    ID              VARCHAR(36) PRIMARY KEY,
    USER_ID         VARCHAR(36) NOT NULL REFERENCES LENS_USERS(ID),
    IMAGE_BASE64    TEXT,
    DESCRIPTION     VARCHAR(2000),
    RESULTS_JSON    VARIANT,
    SOURCE_URL      VARCHAR(2000),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
